version: '3.9'

services:
  database:
    container_name: database
    hostname: database
    image: postgres
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - db
      - all

  webserver:
    container_name: webserver
    build: './backend'
    hostname: webserver
    ports:
      - 3000:3000
    environment:
      - RUST_BACKTRACE=1
      - database__host=database
    profiles:
      - all
    depends_on:
      database:
        condition: service_healthy
