version: '3.9'

services:
  database:
    container_name: database
    hostname: database
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=admin
    profiles:
      - db
      - all

  webserver:
    container_name: webserver
    build: './backend'
    hostname: webserver
    ports:
      - 8000:3000
    environment:
      - RUST_BACKTRACE=1
    profiles:
      - all
